### ISSUE TITLE
./gateway_service_start.sh: /bin/sh^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by einsqing** [eolinker/GoKu-API-Gateway#2]
./gateway_service_start.sh: /bin/sh^M: bad interpreter: No such file or directory

**Comment by eolinker** [comment]
您好，该问题在最新的版本中已修复。

**Comment by creantan** [comment]
docker exec -i -t gateway bash进到容器内部然后vi gateway_service_start.sh,设置文件格式为unix，:set ff=unix
