### ISSUE TITLE
ce版本v3.0.1  bug

### ISSUE THREAD

**Issue by c5433137** [eolinker/goku-api-gateway#24]
管理端与node节点的 心跳机制 导致的 一直简历连接没有释放连接资源的bug。
导致以但运行超过限制打开文件描述符。就会停止服务。

从日志来看是1秒一次的心跳导致的。

2019/09/29 23:45:40 http: Accept error: accept tcp 127.0.0.1:9903: accept4: too many open files; retrying in 1s

**Comment by eolinker** [comment]
感谢您的反馈，我们尽快排查问题

**Comment by c5433137** [comment]
你好 请问是否定位到问题了呢？

**Comment by hmzzrcs** [comment]
你好，我们这边没有重现这个问题，这条日志是心跳打出来的，但是不是因为心跳的原因导致的，能不能提供一下你的系统环境

**Comment by Dot-Liu** [comment]
您好，您所提的上述问题已修复，并且代码应更新，您重新pull下来，重新编译节点文件后重新运行节点即可

**Comment by c5433137** [comment]
好的下班后回去试试，哈哈！

**Comment by c5433137** [comment]
> 您好，您所提的上述问题已修复，并且代码应更新，您重新pull下来，重新编译节点文件后重新运行节点即可
讲道理 这里应该是http 1.1 应该可以复用连接吧，golang 这个库太坑啦

**Comment by c5433137** [comment]
能否提供一下编译后的压缩包呢？
原因：编译提示有些谷歌的包因为网络的原因下载失败，我自己网络暂时没有vpn。
go: golang.org/x/net@v0.0.0-20180906233101-161cd47e91fd: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: connect: connection timed out)
go: error loading module requirements
尝试几次后没有比较好的方案处理这个问题。

**Comment by hmzzrcs** [comment]
[](https://goproxy.io/)
# Enable the go modules feature
export GO111MODULE=on
# Set the GOPROXY environment variable
export GOPROXY=https://goproxy.io

**Comment by c5433137** [comment]
完美解决，感谢！

**Comment by eolinker** [comment]
感谢您的支持，如果您公司已经初步使用我们的产品，欢迎在我们的用户反馈Issue中留言（https://github.com/eolinker/goku-api-gateway/issues/22），您的支持是我们的动力，感谢！
@c5433137

**Comment by peter11420** [comment]
您好,想請問使用docker新增節點會產生[FATA] get config timeout是什麼問題呢
