### ISSUE TITLE
编译报错，不知道怎么回事

### ISSUE THREAD

**Issue by linsijia1002** [eolinker/goku-api-gateway#25]
build/cmd/build-node.sh
ls: cannot access /mnt/gocode/src/goku-api-gateway/app/plugins/: No such file or directory
build goku-node:go build  -o /mnt/gocode/src/goku-api-gateway/out/goku-node-2019101216-15fd948/goku-node /mnt/gocode/src/goku-api-gateway/app/goku-node
can't load package: package /mnt/gocode/src/goku-api-gateway/app/goku-node: import "/mnt/gocode/src/goku-api-gateway/app/goku-node": cannot import absolute path

**Comment by linsijia1002** [comment]
[root@VM_158_121_redhat goku-api-gateway]# pwd
/mnt/gocode/src/goku-api-gateway

**Comment by hmzzrcs** [comment]
完整的包地址是   github.com/eolinker/goku-api-gateway
需要放到  $GOPATH/src/github.com/eolinker/goku-api-gateway 下进行编译

**Comment by hmzzrcs** [comment]
用 go get  github.com/eolinker/goku-api-gateway

**Comment by linsijia1002** [comment]
3.0.0和v3.0.0有什么区别？哪个新

**Comment by linsijia1002** [comment]
> 用 go get github.com/eolinker/goku-api-gateway

**Comment by eolinker** [comment]
你好，如果是下载release版的话，建议下载最新的版本（3.0.1）。

**Comment by linsijia1002** [comment]
好的，我已经下载了3.0.1，但是run起来说我已经启动了。。可是我根本没有启动，也没有在监听7000端口。
[root@VM_158_121_redhat console]# ./run.sh start /mnt/goku-api-gateway/config/goku.conf admin 123456
Error! gateway-console is currently running!

**Comment by linsijia1002** [comment]
[root@VM_158_121_redhat console]# ./run.sh start|restart
-bash: restart: command not found
Error! gateway-console is currently running!

**Comment by Dot-Liu** [comment]
您先删除work目录下的gateway-console.pid文件，重新执行./run.sh start

**Comment by linsijia1002** [comment]
可以了
