### ISSUE TITLE
实现访问限速和重定向

### ISSUE THREAD

**Issue by liuxinfeng123** [eolinker/goku-api-gateway#26]
请教一个问题：如何实现访问一个uri，然后跳转到另一个location上，另外对这个uri进行限速。具体应该怎么配置

**Comment by eolinker** [comment]
你好。
针对第一个问题，你想问的是前端访问api网关，然后网关返回重定向的头部让前端重定向，还是说前端访问api网关，网关转发到后端服务器的时候跟随后端服务器的重定向？

第二个问题，目前开源版本没有限速功能，可以通过自行开发自定义的限速插件来实现。我们的企业版API网关自带有限速插件，如果有兴趣可以联系我们申请试用：
https://www.eolinker.com/#/survey/applyAmsCloud

如果你还有其他的疑问，欢迎加入我们的交流Q群：725853895
