### ISSUE TITLE
3.1.0 增加插件错误

### ISSUE THREAD

**Issue by katydid2005** [eolinker/goku-api-gateway#30]
`panic(0x9c5cc0, 0x109d050)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/eolinker/goku-api-gateway/console/module/plugin/plugin-config.CheckConfig(0xc0001c630b, 0x10, 0x10f5f08, 0x0, 0x0, 0x0, 0x4, 0x2)
	/home/lvyou/goku/goku_code/goku-api-gateway/console/module/plugin/plugin-config/config.go:41 +0x50e
github.com/eolinker/goku-api-gateway/console/controller/plugin.AddPlugin(0xb0d060, 0xc0001ae380, 0xc000304100)
	/home/lvyou/goku/goku_code/goku-api-gateway/console/controller/plugin/plugin.go:64 +0x2f4
net/http.HandlerFunc.ServeHTTP(0xa716d0, 0xb0d060, 0xc0001ae380, 0xc000304100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x10d8b20, 0xb0d060, 0xc0001ae380, 0xc000304100)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000ddee0, 0xb0d060, 0xc0001ae380, 0xc000304100)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00023a0a0, 0xb0e5a0, 0xc0004061c0)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
`

**Comment by helloworld8192** [comment]
CE 版本无法添加插件
在 扩展插件->添加插件->保存 的时候，Response返回
{"resultDesc":"[ERROR]Failed to insert data!","statusCode":"210000","type":"plugin"}

**Comment by eolinker** [comment]
感谢反馈，我们会尽快修复该问题。

**Comment by eolinker** [comment]
您好，3.1.1版本已修复该问题，您可以下载最新的Release文件来使用。
如有疑问，欢迎提交issue或加入我们的用户讨论群（725853895）进行反馈。
