### ISSUE TITLE
重启之后服务就无法再次启动了

### ISSUE THREAD

**Issue by GreatWriter** [eolinker/goku-api-gateway#34]
重启之后服务就无法再次启动了
就会报错。Error! gateway-console is currently running!

命令  ./run.sh start  stop  等等均无效

**Comment by lygtmxbtc** [comment]
> 重启之后服务就无法再次启动了
> 就会报错。Error! gateway-console is currently running!
> 
> 命令 ./run.sh start stop 等等均无效

删除work目录下的gateway-console.pid

**Comment by eolinker** [comment]
您好，您删除work目录下的gateway-console.pid再执行命令即可。

@lygtmxbtc 感谢回复

**Comment by eolinker** [comment]
若您还有问题，欢迎给我们提issue或者加入我们的用户讨论群：725853895，感谢您的支持！
