### ISSUE TITLE
启动节点失败: [FATA] get config timeout

### ISSUE THREAD

**Issue by lygtmxbtc** [eolinker/goku-api-gateway#35]
无论docker环境下，还是本地部署环境下，console环境创建节点后，启动节点都失败。查看log原因是`[FATA] get config timeout`

**Comment by Dot-Liu** [comment]
您好，该问题已修复，其原因是docker镜像默认绑定了本地IP，导致节点容器无法获取配置信息
现镜像已修复更新
您请重新将控制台镜像（goku-api-gateway-ce-console）pull下来，依次重新运行控制台和节点即可
