### ISSUE TITLE
build/cmd/build-console.sh  file path not exist

### ISSUE THREAD

**Issue by jooyyy** [eolinker/goku-api-gateway#36]
build/cmd/build-console.sh:15

![image](https://user-images.githubusercontent.com/30552622/69135571-44c0b780-0af4-11ea-8200-e2fabc15cd64.png)

**Comment by jooyyy** [comment]
It seems that /static folder was ignored, causing a bash running failure.

**Comment by Dot-Liu** [comment]
![image](https://user-images.githubusercontent.com/14105999/69139802-3e363e00-0afc-11ea-9664-260171eb6ce5.png)
The path is shown in the figure

**Comment by jooyyy** [comment]
> ![image](https://user-images.githubusercontent.com/14105999/69139802-3e363e00-0afc-11ea-9664-260171eb6ce5.png)
> The path is shown in the figure

The question is the code in build-console.sh line #15 
> cp -a ${BasePath}/app/console/static/*  ${OUTPATH}/static/
while the "/static/" is ignore by .gitignore file.

**Comment by Dot-Liu** [comment]
Path static has been migrated to the build/console/resource directory in version 3.1.1,like this

![image](https://user-images.githubusercontent.com/14105999/69144506-6aef5300-0b06-11ea-8051-7ba10aca637d.png)

This error can be ignored and will not affect normal use.
