### ISSUE TITLE
启用开放策略时候异常

### ISSUE THREAD

**Issue by please88** [eolinker/goku-api-gateway#39]
docker image id：bd617fc66c8a
eolinker/goku-api-gateway-ce-node      latest              bd617fc66c8a

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xae29a5]

goroutine 22 [running]:
github.com/eolinker/goku-api-gateway/node/gateway.genFactory(0xc0004745b0, 0xcedf80, 0x12e3e00, 0x0)
        /golang/src/github.com/eolinker/goku-api-gateway/node/gateway/router.go:169 +0x75
github.com/eolinker/goku-api-gateway/node/gateway.Parse(0xc0004745b0, 0xcedf80, 0x12e3e00, 0xc000429e68, 0xc000429e90, 0x9458d6, 0xc0000a1510)
        /golang/src/github.com/eolinker/goku-api-gateway/node/gateway/router.go:29 +0x4c
github.com/eolinker/goku-api-gateway/node/server.(*Server).FlushRouter(0xc000085310, 0xc0004745b0)
        /golang/src/github.com/eolinker/goku-api-gateway/node/server/server.go:99 +0x56
github.com/eolinker/goku-api-gateway/node/console.(*Console).AddListen.func1(0xb4e740, 0xc0004745b0)
        /golang/src/github.com/eolinker/goku-api-gateway/node/console/config.go:62 +0x40
github.com/eolinker/goku-api-gateway/common/listener.(*Listener).Call(0xc000066080, 0xb4e740, 0xc0004745b0)
        /golang/src/github.com/eolinker/goku-api-gateway/common/listener/listener.go:47 +0xb6
github.com/eolinker/goku-api-gateway/node/console.listenConfig.func1(0xcfc260, 0xc0000a0a40, 0xc00009a180, 0x2a, 0x7ffceeda9e65, 0x20)
        /golang/src/github.com/eolinker/goku-api-gateway/node/console/config.go:96 +0x12b
created by github.com/eolinker/goku-api-gateway/node/console.listenConfig
        /golang/src/github.com/eolinker/goku-api-gateway/node/console/config.go:75 +0x168
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xae29a5]

goroutine 1 [running]:
github.com/eolinker/goku-api-gateway/node/gateway.genFactory(0xc00010c1a0, 0xcedf80, 0x12e3e00, 0x0)
        /golang/src/github.com/eolinker/goku-api-gateway/node/gateway/router.go:169 +0x75
github.com/eolinker/goku-api-gateway/node/gateway.Parse(0xc00010c1a0, 0xcedf80, 0x12e3e00, 0x1, 0x2, 0xc00002d760, 0x1)
        /golang/src/github.com/eolinker/goku-api-gateway/node/gateway/router.go:29 +0x4c
github.com/eolinker/goku-api-gateway/node/server.(*Server).ServerWidthConfig(0xc00002d580, 0xc00010c1a0, 0x0, 0x0)
        /golang/src/github.com/eolinker/goku-api-gateway/node/server/server.go:69 +0xc6
github.com/eolinker/goku-api-gateway/node/server.(*Server).ServerWidthConsole(0xc00002d580, 0xc00008a870, 0x7ffda944ce49, 0x10)
        /golang/src/github.com/eolinker/goku-api-gateway/node/server/server.go:57 +0xf9
main.main()
        /golang/src/github.com/eolinker/goku-api-gateway/app/node/main.go:25 +0x1d9

**Comment by Dot-Liu** [comment]
好的，我们排查一下，感谢您的反馈

**Comment by Dot-Liu** [comment]
上述问题已修复，请重新pull镜像或者安装包
