### ISSUE TITLE
is it support window system?

### ISSUE THREAD

**Issue by JinShng** [eolinker/GoKu-API-Gateway#4]
is it support windows system? I run `go build goku-ce.go` , something has error
`$ go build goku-ce.go`
`# goku-ce/goku
goku\endless.go:62:3: undefined: syscall.SIGUSR1
goku\endless.go:63:3: undefined: syscall.SIGUSR2
goku\endless.go:66:3: undefined: syscall.SIGTSTP
goku\endless.go:113:5: undefined: syscall.SIGUSR1
goku\endless.go:114:5: undefined: syscall.SIGUSR2
goku\endless.go:117:5: undefined: syscall.SIGTSTP
goku\endless.go:121:5: undefined: syscall.SIGUSR1
goku\endless.go:122:5: undefined: syscall.SIGUSR2
goku\endless.go:125:5: undefined: syscall.SIGTSTP
goku\endless.go:225:3: undefined: syscall.Kill
goku\endless.go:225:3: too many errors
`

**Comment by eolinker** [comment]
Only for linux.
