### ISSUE TITLE
build/cmd/build-console.sh

### ISSUE THREAD

**Issue by flanchegong** [eolinker/goku-api-gateway#40]
build/cmd/build-console.sh [3.1]
build/cmd/build-console.sh
build console:go build  -o /root/go-workspace/src/github.com/eolinker/goku-api-gateway/out/console-[3.1]/console /root/go-workspace/src/github.com/eolinker/goku-api-gateway/app/console
cp: 无法获取"/root/go-workspace/src/github.com/eolinker/goku-api-gateway/app/console/static/*" 的文件状态(stat): 没有那个文件或目录

**Comment by eolinker** [comment]
感谢您的反馈，我们先排查一下是否有该问题，若有该问题，我们会尽快修复。

**Comment by zkenstein** [comment]
> build/cmd/build-console.sh [3.1]
> build/cmd/build-console.sh
> build console:go build -o /root/go-workspace/src/github.com/eolinker/goku-api-gateway/out/console-[3.1]/console /root/go-workspace/src/github.com/eolinker/goku-api-gateway/app/console
> cp: 无法获取"/root/go-workspace/src/github.com/eolinker/goku-api-gateway/app/console/static/*" 的文件状态(stat): 没有那个文件或目录

same issue here

**Comment by zkenstein** [comment]
What I am doing is copy the static folder to app/console

**Comment by please88** [comment]
build/cmd/build-console.sh
注释一行
`#cp -a ${BasePath}/app/console/static/*  ${OUTPATH}/static/`

**Comment by Dot-Liu** [comment]
请更新最新的安装包，上述问题已修复
