### ISSUE TITLE
node build failed!!

### ISSUE THREAD

**Issue by AHAQ-DL** [eolinker/goku-api-gateway#45]
尝试编译node工程，但是编译脚本报错，以下为错误信息:

`github.com/eolinker/goku-api-gateway/node/console`
`node/console/config.go:29:10: undefined: Console`
`node/console/config.go:58:10: undefined: Console`
`node/console/console.go:17:6: ConfigCallbackFunc redeclared in this block
        previous declaration at node/console/config.go:19:6`

**Comment by eolinker** [comment]
node编译问题已修复
