### ISSUE TITLE
节点启动正常，但请求接口总是报[ERROR]StrategyID dose not exist!异常

### ISSUE THREAD

**Issue by flazx** [eolinker/goku-api-gateway#52]
console和节点都run起来了，但请求任何数据都显示StrategyID不存在，访问策略是开放策略也不行。
后台日志显示请求状态 500~~

![image](https://user-images.githubusercontent.com/122400/75626088-65260500-5bff-11ea-9782-3ce2697d15f7.png)
![image](https://user-images.githubusercontent.com/122400/75626104-84bd2d80-5bff-11ea-9a8d-32067fbaf4a8.png)

**Comment by TomJack1** [comment]
配置管理 生成没得。里面没有版本 会报这个错

**Comment by flazx** [comment]
生成配置了，但还是不行！
![image](https://user-images.githubusercontent.com/122400/75741652-31a1c280-5d46-11ea-8665-72bdd6f0d525.png)
![image](https://user-images.githubusercontent.com/122400/75741668-42523880-5d46-11ea-80f3-448e6525e646.png)
![image](https://user-images.githubusercontent.com/122400/75741680-4a11dd00-5d46-11ea-8091-8b37aeac2769.png)

**Comment by felix0080** [comment]
感觉不太成熟，用起来不太放心，

**Comment by eolinker** [comment]
网关的正常使用是没有问题的，抱歉没法复现您的问题。您可以加入我们的用户交流群与我们进行交流：725853895

**Comment by iarno** [comment]
你们那文档太费劲了
