### ISSUE TITLE
为什么非要一个策略id

### ISSUE THREAD

**Issue by felix0080** [eolinker/goku-api-gateway#53]
必须侵入用户非常不友好，在请求头 表单等处增加一个Strategy-Id 在体验上太差

**Comment by eolinker** [comment]
您好，开源版的策略ID相当于是用户或客户端的识别标志，如果您不想加上策略ID，可以采用里面的开放策略。

企业版的路由规则会灵活很多，可以根据自定义Header、Query和Location来路由，没有侵入性，具体的介绍可以查看教程：https://help.eolinker.com/#/tutorial/?groupID=c-460&productID=14

后续开源版的路由规则也会优化，敬请期待。

**Comment by felix0080** [comment]
![image](https://user-images.githubusercontent.com/15978779/75833822-32ddf880-5df5-11ea-8c42-810c6fe21c3a.png)
开放策略显示的已停用，可以通过什么方式开启吗？

**Comment by felix0080** [comment]
> 您好，开源版的策略ID相当于是用户或客户端的识别标志，如果您不想加上策略ID，可以采用里面的开放策略。
> 
> 企业版的路由规则会灵活很多，可以根据自定义Header、Query和Location来路由，没有侵入性，具体的介绍可以查看教程：https://help.eolinker.com/#/tutorial/?groupID=c-460&productID=14
> 
> 后续开源版的路由规则也会优化，敬请期待。

![image](https://user-images.githubusercontent.com/15978779/75833893-5d2fb600-5df5-11ea-9c39-63a767edd148.png)
开放策略已停用，可以使用什么配置方式开启吗
