### ISSUE TITLE
开放策略已停用，可以通过什么方式开启吗？

### ISSUE THREAD

**Issue by felix0080** [eolinker/goku-api-gateway#54]
![image](https://user-images.githubusercontent.com/15978779/75833924-7fc1cf00-5df5-11ea-86b3-d95f700c05cd.png)

**Comment by eolinker** [comment]
您好，在控制台的一级菜单选择【访问策略】，进入开放策略内页，侧边栏选择【策略管理】，在这里可以启用开放策略。
