### ISSUE TITLE
你好！为什么我的在添加好集群后，进入集群想添加分组会失败？

### ISSUE THREAD

**Issue by fws20060501** [eolinker/goku-api-gateway#58]
我是使用 docker部署的
版本：
eolinker/goku-api-gateway-ce-console:3.1.3
eolinker/goku-api-gateway-ce-node:3.1.3

在UI上的节点集群内添加分组，提示以下的报错：
{"resultDesc":"[ERROR]Fail to insert data!","statusCode":"280000","type":"nodeGroup"}

**Comment by eolinker** [comment]
您提的问题已修复，请重新pull并运行控制台镜像
