### ISSUE TITLE
您好，策略组ID支持自定义或者不显示在路由上面吗？

### ISSUE THREAD

**Issue by zouhuigang** [eolinker/GoKu-API-Gateway#6]
因为随机出来的这个KLxiHu策略组id，发给别人，不太好理解，而且如果不想改变原来已有的api路径，怎么做到无缝切换？是需要在nginx前面再加一层转发吗？

例如，开始给别人的api是：

https://api.apishop.net/common/oil/getOilPriceToday

切换成goku-api-gateway之后，仍然想使用这个地址，而不用下面的地址：

http://192.168.199.232:6602/demo_gateway/KLxiHu/common/oil/getOilPriceToday

**Comment by eolinker** [comment]
近期会更新，策略ID将支持放在头部。

**Comment by zouhuigang** [comment]
好的，感谢。建议再设置一个默认的策略id，没有传策略id过来，就默认使用。这样方便url切换过来。

**Comment by eolinker** [comment]
V2.1.4版本的策略ID已支持放入头部；
关于第二点建议，如果没传策略ID，网关自动帮您带上，这样有两点不好的地方：
1. 用户相当于只要知道了地址就能调用，完全开放了后端服务，并不建议这样做；
2. 策略代表的是用户，有一个所有用户都能用的策略，就不能够区分用户进行流量限制。
