### ISSUE TITLE
使用consul服务发现，拉取的服务地址有误

### ISSUE THREAD

**Issue by stevenghost** [eolinker/goku-api-gateway#60]
在consul_catalog.go中

`hosts[i] = d.instanceFactory.General(instance.Node.Address, instance.Service.Port, 1)`

应该是

`hosts[i] = d.instanceFactory.General(instance.Service.Address, instance.Service.Port, 1)`

这样才对把？

**Comment by zuozhiwen** [comment]
我测试发现也不行，确实返回了consul本身的IP，应该就是上面代码展示的Node的地址。这么严重的问题都没人修复吗？我们我们这边还在考虑企业版，看到这样的应付模式根本都不敢考虑了。

**Comment by smile-luobin** [comment]
提个PATCH改下吧

**Comment by botsphp** [comment]
牛逼的功能都在企业版

**Comment by eolinker** [comment]
您好，感谢您的反馈，我们将记录问题并反馈给技术同事，若存在问题，争取尽快修复更新。
