### ISSUE TITLE
官方教程会导致 StrategyID dose not exist!异常，可以完善它吗？

### ISSUE THREAD

**Issue by Fu-Changjie** [eolinker/goku-api-gateway#61]
关于 #52 “StrategyID dose not exist!异常” 这个错误， 我在跟随[快速入门教程](https://help.eolinker.com/#/tutorial/?groupID=c-307&productID=19)时也遇到了。

在尝试了 [TomJack1](https://github.com/eolinker/goku-api-gateway/issues/52#issuecomment-593190734)  的方法后问题得到了解决

可以考虑更新以下此教程并添加关于 保存并发布配置 的相关内容吗？

**Comment by eolinker** [comment]
感谢您的反馈，教程已更新完毕！抱歉给你们带来不便。
