### ISSUE TITLE
duplicate instance

### ISSUE THREAD

**Issue by zhao459399177** [eolinker/goku-api-gateway#62]
console 和node 不能在同一台电脑 的dokcer 中运行呀，错误duplicate instance

**Comment by Dot-Liu** [comment]
可以在同一台电脑的docker运行，您需要看看是否重复注册同一个节点了，或者提供更加详细的信息截图以供排查

**Comment by zhao459399177** [comment]
我的操作
1、docker network rm docker_gwbridge
2、docker network create --driver bridge --subnet=172.18.12.0/24 --gateway=172.18.12.1 goku-ce
3、docker run -dt -p 7000:7000 \
-v /app/goku-ce/work:/app/goku-ce/console/work \
-e GOKU_ADMIN_PASSWORD=123456 \
--network=goku-ce \
--ip 172.18.12.2 \
--name goku-ce-console \
eolinker/goku-api-gateway-ce-console
4、docker run -dt -p 6689:6689 \
--network goku-ce \
--ip 172.18.12.3 \
-v /app/goku-ce/node/work:/app/goku-ce/node/work \
-e GOKU_ADMIN_ADDRESS=172.18.12.2:7005 \
-e INSTANCE=6d0d999f9a60d51eaf0b5bb0226290ef \
eolinker/goku-api-gateway-ce-node

其中的node 节点的容器状态不是运行中的，查看日志是[FATA] duplicate instance

**Comment by Dot-Liu** [comment]
INSTANCE是个变量，您需要进行修改，改成您控制台页面显示的node key值
![image](https://user-images.githubusercontent.com/14105999/81154295-5a4c6f80-8fb6-11ea-9db4-55a0afec3dc6.png)

**Comment by zhao459399177** [comment]
多谢指导
