### ISSUE TITLE
功能比较简陋

### ISSUE THREAD

**Issue by lchb369** [eolinker/GoKu-API-Gateway#7]
建议：
1,根据每个API接口设置访问策略，更加灵活。访问网关时不建议URL中还跟一个策略ID，没有必要
2,统计信息应该能统计每个接口响时间。这个至关重要。
3,看源码访问量统计+1都会开个单独协程，比较怀疑在高并发情况会不会有问题。

**Comment by eolinker** [comment]
1. 开源版网关早已兼容在header放策略ID。
2. 根据接口设置策略、详细的监控功能等，这些在我们的企业版网关里均有提供，欢迎到官网申请试用。
目前公司的重心主要是放在企业版网关上，开源版会不定时更新。
