### ISSUE TITLE
是否支持mysql数据库？

### ISSUE THREAD

**Issue by iarno** [eolinker/goku-api-gateway#70]
mysql数据库不支持吗？
`panic: need:[github.com/eolinker/goku-api-gateway/server/dao.dao.BalanceDao github.com/eolinker/goku-api-gateway/server/dao.dao.NodeDao github.com/eolinker/goku-api-gateway/server/dao.dao.APIDao github.com/eolinker/goku-api-gateway/server/dao.dao.GuestDao github.com/eolinker/goku-api-gateway/server/dao.dao.UserDao github.com/eolinker/goku-api-gateway/server/dao.dao.APIPluginDao github.com/eolinker/goku-api-gateway/server/dao.dao.StrategyDao github.com/eolinker/goku-api-gateway/server/dao.dao.APIGroupDao github.com/eolinker/goku-api-gateway/server/dao.dao.ProjectDao github.com/eolinker/goku-api-gateway/server/dao.dao.StrategyPluginDao github.com/eolinker/goku-api-gateway/server/dao.dao.VersionDao github.com/eolinker/goku-api-gateway/server/dao.dao.MonitorModulesDao github.com/eolinker/goku-api-gateway/server/dao.dao.ServiceDao github.com/eolinker/goku-api-gateway/server/dao.dao.PluginDao github.com/eolinker/goku-api-gateway/server/dao.dao.StrategyGroupDao github.com/eolinker/goku-api-gateway/server/dao.dao.ClusterDao github.com/eolinker/goku-api-gateway/server/dao.dao.NodeGroupDao github.com/eolinker/goku-api-gateway/server/dao.dao.VersionConfigDao github.com/eolinker/goku-api-gateway/server/dao.dao.GatewayDao github.com/eolinker/goku-api-gateway/server/dao.dao.ConfigLogDao github.com/eolinker/goku-api-gateway/server/dao.dao.APIStrategyDao github.com/eolinker/goku-api-gateway/server/dao.dao.ImportDao github.com/eolinker/goku-api-gateway/server/dao.dao.AuthDao github.com/eolinker/goku-api-gateway/server/dao.dao.BalanceUpdateDao]`

**Comment by eolinker** [comment]
您好，开源版网关定位是轻量级，不支持Mysql；企业版网关使用的是Mysql数据库。
