### ISSUE TITLE
 /app/console/static 在哪里

### ISSUE THREAD

**Issue by zyssyz123** [eolinker/goku-api-gateway#72]
编译的时候看到 /build/cmd/build-console.sh 中需要 cp /app/console/static/* ,但是对应目录下没有该文件夹

**Comment by smile-luobin** [comment]
我也是编译的时候没找到 /app/console/static/* ,

**Comment by Dot-Liu** [comment]
这个报错可以忽略，实际上编译使用了build/console/resources下的static目录，得到编译后的包已经包含
