### ISSUE TITLE
[ERROR]Missing Strategy ID!

### ISSUE THREAD

**Issue by clh-cod** [eolinker/goku-api-gateway#79]
您好，我在部署一个console和node后，调用API报错[ERROR]Missing Strategy ID!，且我已经启动了`开发策略`，请问是哪里配置错了呢。

**Comment by clh-cod** [comment]
使用`开放策略`是需要传递`Strategy-Id`的请求头的吧，换成普通策略，加上`Strategy-Id`后就成功了

**Comment by eolinker** [comment]
有可能是您开启了开放策略后，没有发布配置

**Comment by eolinker** [comment]
开放策略是不需要传递策略ID的，普通策略需要传递策略ID，修改完配置确认无误后，记得发布配置才生效。
