### ISSUE TITLE
app/config/server.go listen_port config not working

### ISSUE THREAD

**Issue by Ricord** [eolinker/goku-api-gateway#83]
I changed the listen_port from 7000 to a custom value 8001, however the console still listen to 7000.

From the code I can see, it log out the correct listen_port, but still use 7000

The file path is "/app/config/server.go", line 27

```go
	port, has := conf.Get("listen_port")
	if has {
		go func() {
			log.Print("Listen: ", port)
			log.Print("Start Successfully!")
			err := http.ListenAndServe(":7000", router())

			ec <- err
		}()
	} else {
		log.Panic("[ERROR] Illegal listen port!")
	}
```
Please make the http listen to port ,thanks.

**Comment by Dot-Liu** [comment]
Thanks
This problem has been fixed.
